# SPDX-License-Identifier: GPL-2.0
microchip-gfx2d-y := \
	mchp_gfx2d_cmd.o \
	mchp_gfx2d_drv.o \
	mchp_gfx2d_gem.o \
	mchp_gfx2d_ioctl.o

obj-$(CONFIG_DRM_MICROCHIP_GFX2D) += microchip-gfx2d.o

mpfs-dpsub-y := mpfs_kms.o mpfs_dpsub.o
obj-$(CONFIG_DRM_MPFS_DPSUB) += mpfs-dpsub.o

