# SPDX-License-Identifier: GPL-2.0
#
# Makefile for MPFS Motor Control IIO drivers
#

obj-$(CONFIG_IIO_MPFS_MC_ADC) += mpfs_mc_adc.o
obj-$(CONFIG_IIO_MPFS_MC_PICON) += mpfs_mc_picon.o
obj-$(CONFIG_IIO_MPFS_MC_PWM) += mpfs_mc_pwm.o
obj-$(CONFIG_IIO_MPFS_MC_RATELIM) += mpfs_mc_ratelim.o
obj-$(CONFIG_IIO_MPFS_MC_SQMNG) += mpfs_mc_sqmng.o
obj-$(CONFIG_IIO_MPFS_MC_STPTHETA) += mpfs_mc_stptheta.o
